"""Server-side pieces: the shared Traefik + cloudflared stack, deployment listing, URL probing."""

from __future__ import annotations

import json
import re
import time
import urllib.error
import urllib.request
from dataclasses import dataclass

from quick_deploy import __version__
from quick_deploy.errors import QDError
from quick_deploy.project import NETWORK
from quick_deploy.remote import Remote, heredoc

MIN_COMPOSE = (2, 24)  # for `!reset` in override files

SYSTEM_COMPOSE = f"""\
# generated by qd; do not edit
services:
  traefik:
    image: traefik:v3
    container_name: qd-traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network={NETWORK}
      - --entrypoints.web.address=:80
      # Only cloudflared can reach this entrypoint, so trust its X-Forwarded-* headers
      # (apps then see X-Forwarded-Proto: https).
      - --entrypoints.web.forwardedheaders.insecure=true
      - --log.level=WARN
    volumes:
      # DOCKER_SOCK is detected by bootstrap (differs for rootless docker).
      - ${{DOCKER_SOCK:-/var/run/docker.sock}}:/var/run/docker.sock:ro
    security_opt:
      - label=disable  # SELinux (Fedora, RHEL) blocks the docker socket otherwise; a no-op elsewhere
    networks: [{NETWORK}]
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: qd-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${{TUNNEL_TOKEN}}
    depends_on: [traefik]
    networks: [{NETWORK}]
networks:
  {NETWORK}:
    name: {NETWORK}
    external: true
"""

# Prints key=value lines describing the server's state; never fails.
STATUS_SCRIPT = r"""
v() { "$@" 2>/dev/null || true; }
echo "os=$(. /etc/os-release 2>/dev/null; echo $ID $ID_LIKE)"
echo "docker=$(v docker version --format '{{.Server.Version}}')"
echo "compose=$(v docker compose version --short)"
echo "rsync=$(command -v rsync || true)"
echo "network=$(v docker network inspect qd --format ok)"
echo "traefik=$(v docker inspect -f '{{.State.Status}}' qd-traefik)"
echo "cloudflared=$(v docker inspect -f '{{.State.Status}}' qd-cloudflared)"
echo "tunnel_connections=$( (docker logs --since 24h qd-cloudflared 2>&1 || true) | grep -c 'Registered tunnel connection' || true)"
"""


def server_status(r: Remote) -> dict[str, str]:
    out = r.output(STATUS_SCRIPT)
    return dict(line.split("=", 1) for line in out.splitlines() if "=" in line)


def version_at_least(v: str, minimum: tuple[int, int]) -> bool:
    m = re.match(r"v?(\d+)\.(\d+)", v.strip())
    return bool(m) and (int(m[1]), int(m[2])) >= minimum


# Install hints, keyed by the IDs in /etc/os-release. The first of `$ID $ID_LIKE`
# (e.g. "rocky rhel centos fedora") found in a table wins.
_PKG = {
    "fedora": "sudo dnf install -y", "rhel": "sudo dnf install -y", "centos": "sudo dnf install -y",
    "debian": "sudo apt-get install -y", "ubuntu": "sudo apt-get install -y",
    "arch": "sudo pacman -S --needed",
    "opensuse": "sudo zypper install -y", "suse": "sudo zypper install -y",
    "alpine": "sudo apk add",
}  # fmt: skip
_GET_DOCKER = "curl -fsSL https://get.docker.com | sudo sh && sudo systemctl enable --now docker"
# get.docker.com rejects RHEL clones (Rocky, Alma); Docker's RHEL repo works for all of them.
_RHEL_DOCKER = (
    "sudo dnf install -y dnf-plugins-core"
    " && sudo dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo"
    " && sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin"
    " && sudo systemctl enable --now docker"
)
_DOCKER = {
    "fedora": "sudo dnf install -y moby-engine docker-compose && sudo systemctl enable --now docker",
    "rhel": _RHEL_DOCKER, "centos": _RHEL_DOCKER, "debian": _GET_DOCKER, "ubuntu": _GET_DOCKER,
    "arch": "sudo pacman -S --needed docker docker-compose && sudo systemctl enable --now docker",
    "opensuse": "sudo zypper install -y docker docker-compose && sudo systemctl enable --now docker",
    "suse": "sudo zypper install -y docker docker-compose && sudo systemctl enable --now docker",
    "alpine": "sudo apk add docker docker-cli-compose && sudo rc-update add docker && sudo service docker start",
}  # fmt: skip


def _lookup(table: dict[str, str], os_ids: str) -> str | None:
    return next((table[w] for w in os_ids.split() if w in table), None)


def pkg_hint(os_ids: str, *pkgs: str) -> str:
    """Command installing pkgs on the server's distro."""
    cmd = _lookup(_PKG, os_ids)
    return f"{cmd} {' '.join(pkgs)}" if cmd else f"install {' '.join(pkgs)} with the server's package manager"


def docker_hint(os_ids: str) -> str:
    """Commands making docker usable by the ssh user on the server's distro."""
    install = _lookup(_DOCKER, os_ids) or "install Docker Engine + compose plugin: https://docs.docker.com/engine/install/"
    group = "sudo addgroup $USER docker" if "alpine" in os_ids.split() else "sudo usermod -aG docker $USER"
    return f"{install}\n  {group}   # then log out and back in (or use rootless docker)"


# Where the docker CLI talks to: honours rootless docker's context, else the default socket.
_DETECT_SOCK = """\
sock=$(docker context inspect --format '{{.Endpoints.docker.Host}}' 2>/dev/null || true)
case "$sock" in unix://*) sock=${sock#unix://} ;; *) sock=/var/run/docker.sock ;; esac
"""


def bootstrap(r: Remote, tunnel_token: str) -> None:
    if not re.fullmatch(r"[A-Za-z0-9+/=_-]+", tunnel_token):
        raise QDError("tunnel token has unexpected characters")
    r.run(
        'mkdir -p "$QD/system" "$QD/apps"\n'
        f"docker network inspect {NETWORK} >/dev/null 2>&1 || docker network create {NETWORK} >/dev/null\n"
        'cd "$QD/system"\n'
        "umask 077\n"
        + heredoc(".env", f"TUNNEL_TOKEN={tunnel_token}")
        + _DETECT_SOCK
        + 'echo "DOCKER_SOCK=$sock" >> .env\n'
        + heredoc("compose.yml", SYSTEM_COMPOSE)
        + "docker compose -p qd-system up -d --pull always --remove-orphans\n"
    )


@dataclass
class App:
    name: str
    url: str
    source: str
    source_host: str
    mode: str
    service: str
    port: int
    deployed_at: str
    status: str = "unknown"  # running | degraded | stopped | missing

    def to_dict(self) -> dict:
        return dict(self.__dict__)


LIST_SCRIPT = r"""
for f in "$QD"/apps/*/meta.json; do
  if [ -f "$f" ]; then cat "$f"; echo; fi
done
echo "---QD-PS---"
docker ps -a --filter label=com.docker.compose.project --format '{{.Label "com.docker.compose.project"}}|{{.State}}'
"""


def list_apps(r: Remote) -> dict[str, App]:
    metas, _, ps = r.output(LIST_SCRIPT).partition("---QD-PS---\n")
    states: dict[str, list[str]] = {}
    for line in ps.splitlines():
        project, _, state = line.partition("|")
        states.setdefault(project, []).append(state)
    apps = {}
    for line in metas.splitlines():
        if not line.strip():
            continue
        try:
            m = json.loads(line)
            app = App(**{k: m.get(k) for k in App.__dataclass_fields__ if k != "status"})
        except (ValueError, TypeError):
            continue
        s = states.get(f"qd-{app.name}", [])
        running = s.count("running")
        app.status = "missing" if not s else "running" if running == len(s) else "stopped" if not running else "degraded"
        apps[app.name] = app
    return apps


# --- reachability -------------------------------------------------------------

TRAEFIK_404 = "404 page not found"


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *args, **kwargs):
        return None


def probe(url: str, timeout: float = 10) -> tuple[int | None, str]:
    """GET url without following redirects; return (status, start of body)."""
    opener = urllib.request.build_opener(_NoRedirect)
    req = urllib.request.Request(url, headers={"User-Agent": f"quick-deploy/{__version__}"})
    try:
        with opener.open(req, timeout=timeout) as resp:
            return resp.status, resp.read(64).decode(errors="replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read(64).decode(errors="replace")
    except (urllib.error.URLError, OSError):
        return None, ""


def app_is_up(status: int | None, body: str) -> bool:
    """True once the app itself answers (not a tunnel/proxy error or Traefik's no-route 404)."""
    if status is None or status in (502, 503, 504) or 520 <= status <= 530:
        return False
    return not (status == 404 and body.strip() == TRAEFIK_404)


def wait_until_up(url: str, timeout: float) -> tuple[bool, int | None]:
    deadline = time.monotonic() + timeout
    status = None
    while True:
        status, body = probe(url)
        if app_is_up(status, body):
            return True, status
        if time.monotonic() >= deadline:
            return False, status
        time.sleep(2)
